### ISSUE TITLE
Add A License

### ISSUE THREAD

**Issue by joeblau** [mortenjust/cleartext-mac#12]
Could you please add a license so contributors are clear about their contributions.

**Comment by davelab6** [comment]
+1 I was very sad to see this great project has no license :(

**Comment by davelab6** [comment]
I was very sad to see this great project has no license :(

**Comment by mortenjust** [comment]
I added a GNU v3 license. Let me know if you think it should be different.

**Comment by joeblau** [comment]
@mortenjust Thanks!
