### ISSUE TITLE
Add languages

### ISSUE THREAD

**Issue by DotTheI** [mortenjust/cleartext-mac#20]
Would be cool if the application could work with languages other than English

**Comment by liyuankui** [comment]
There are already several other languages.

**Comment by DotTheI** [comment]
@liyuankui My bad: Danish and Dutch are included. Better than just English, but still not enough for majority of people.

**Comment by holgerkrupp** [comment]
just fork it, create a list of words for your desired language (can often be found on the internet already - best from university websites) and create a pull request.

**Comment by ffesseler** [comment]
maybe it would be better if the app allows to upload your own language file so we don't have to open a pull request for each new list

**Comment by SamuelPoquette** [comment]
I'm currently working on adding many more languages - French, Spanish, Portuguese, German, Finnish, Swedish, Icelandic, Czech, Albanian, Serbian, Croatian, and Indonesian.

**Comment by mortenjust** [comment]
These languages including a few more have been merged and will be available in the next release
