### ISSUE TITLE
Suggestion: Rename to "NewSpeak"

### ISSUE THREAD

**Issue by scottbyrns** [mortenjust/cleartext-mac#26]
Sorry, couldn't help my self :P

**Comment by seanohue** [comment]
Doubleplusgood.

**Comment by Rayraegah** [comment]
Sounds like a dialog/voice/speech option from the Team17's Worms title. I approve.
http://worms.wikia.com/wiki/Speech

**Comment by mortenjust** [comment]
Fun.
