### ISSUE TITLE
Licencing 

### ISSUE THREAD

**Issue by joereddington** [mortenjust/cleartext-mac#3]
Hi - I didn't see a licence on the project - I was hoping to make use of the en.txt file - are you retaining a licence on it? 

Joe

**Comment by mortenjust** [comment]
Hey Joe - It's from the Google Trillion Words corpus. There's a cleaned up file here https://github.com/first20hours/google-10000-english

**Comment by davelab6** [comment]
AMAZING!! 🎉 

That's my favourite :)
