### ISSUE TITLE
Application menu says "Hide Simpler"

### ISSUE THREAD

**Issue by sebm** [mortenjust/cleartext-mac#32]
repro step: in the latest version ("Version 1.31 (3)"), click the "Cleartext" button in the menubar

<img width="200" alt="screen shot 2016-04-06 at 2 02 22 pm" src="https://cloud.githubusercontent.com/assets/188161/14332845/5f50db36-fc00-11e5-89e4-334851c604ae.png">

**Comment by DevJaco** [comment]
This issue has been corrected.
