### ISSUE TITLE
Pressing tab often crashes when at beginning of document

### ISSUE THREAD

**Issue by skull-squadron** [mortenjust/cleartext-mac#33]
Steps to reproduce
1. Launch Cleartext
2. Type "z"
3. Press ⌘-a
4. Press delete
5. Press tab

Also crashes
1. Launch Cleartext
2. Type "z"
3. Press Ctrl-a
4. Press tab

Doesn't crash
1. Launch Cleartext
2. Press tab

**Comment by mortenjust** [comment]
A fix has been merged. Thanks for reporting, it will be included in the the next version
