### ISSUE TITLE
Pressing space when the first word is selected breaks the editor

### ISSUE THREAD

**Issue by dancek** [mortenjust/cleartext-mac#35]
If space is pressed with the first word selected, nothing can be typed any more. My first time trying this, I started with <forbidden word> <comma> <space> and instantly the editor broke. Guess I'm that good at beta testing.

Three different ways to reproduce that I find realistic (on Mac, version 1.31):
1. Start by typing `Wow,` (with a space in the end)
2. You can't type any more.

---
1. Type an incomplete sentence such as `so cool`
2. Move cursor to the beginning.
3. Type `Wow,` (with a space in the end)
4. You can't type any more.

---
1. Write anything.
2. Select the first word manually.
3. Press space (accidentally?).
4. You can't type any more.

**Comment by hamishwyatt** [comment]
Same issue with Return key:
1. Type any "complex" word
2. It will then be highlighted
3. Press Return key
4. It will then be on new line
5. Press Return key again
6. Text disappears, cursor jumps down line and no further typing happens

**Comment by mortenjust** [comment]
Fixed and tested in master—thanks for the detailed bug report and the fix!
