### ISSUE TITLE
Where is the word list?

### ISSUE THREAD

**Issue by qwertie** [mortenjust/cleartext-mac#40]
Hi.... I see that the en.txt file has several thousand words in it. Where is the list of 1000 words in the repo, and what was the original source of the list?

**Comment by gendium** [comment]
Is it possible that the text file just includes the different tenses for verbs? Would that be allowed? Because I just searched for "surpri-" and i got Surprised, Surprises, Surprise and Surprising.

**Comment by ghost** [comment]
@qwertie https://github.com/mortenjust/cleartext-mac/blob/master/Simpler/en.txt, this is the file that the editor uses to look up I think. 

Yep, @gendium the file has more than 1000 entries because even stop words and different tenses for verbs are included.

**Comment by mortenjust** [comment]
That's right. Conjugations seem like a natural thing to include. Currently English and Dutch includes these. I'd love to get more conjugation lists, or implement this programmatically, see #56
