### ISSUE TITLE
Allow names of people, countries, and languages

### ISSUE THREAD

**Issue by kMaiSmith** [mortenjust/cleartext-mac#41]
I want to use this to have some fun changing news pieces to simple words, but it is hard to do when I cannot use names - such as those of countries, languages and people.  

I would like to be able to add a word as a name when the first letter is high case, instead of the word being quickly removed.

**Comment by DevJaco** [comment]
I have created a pull request for the issue

**Comment by mortenjust** [comment]
Merged and included in the next version. Thanks!
