### ISSUE TITLE
People who like simple words may also like simple operating systems.

### ISSUE THREAD

**Issue by cantonbecker** [mortenjust/cleartext-mac#42]
Any chance of making this app backwards compatible for at least 10.9.x? Was surprised to launch this app and see that it _requires_ 10.11 or later. I love the idea! Can't wait to try it. Elsewise I'll be mired in excessively obtuse phraseology evermore.

![screenshot 2016-04-08 08 29 43](https://cloud.githubusercontent.com/assets/4149987/14386923/1e11037a-fd64-11e5-830e-cea94bea04ea.png)

**Comment by hippophagy** [comment]
Yes please! I am running 10.10.5 at work and if I upgrade just for your editor I think IT will kill me.

**Comment by mortenjust** [comment]
Shouldn't be a problem. The 10.11 flag could just be a mistake

**Comment by mortenjust** [comment]
Cleartext should be running on 10.10 and up from the next release.
