### ISSUE TITLE
Trump Mode Doesn't Allow "HUGE"

### ISSUE THREAD

**Issue by Envark** [mortenjust/cleartext-mac#45]
While not one of the most commonly used words overall, HUGE is very commonly used by Trump.

**Comment by GenoD** [comment]
@Envark Take into account that Morten trained it with only "a few of Trump's best known speeches". This probably excludes debates, rallys, etc.

**Comment by smscotten** [comment]
Confirmed. I even tried spelling it 'yuge'.

**Comment by mortenjust** [comment]
merged
