### ISSUE TITLE
Menubar > Cleartext says "About Simpler" not "About Cleartext"

### ISSUE THREAD

**Issue by MoritzFago** [mortenjust/cleartext-mac#5]

**Comment by matthewspear** [comment]
This seems easy enough to fix - would you like me to do it?

From the code it looks like a direct, storyboard change for the application menu:
- About Simpler
- Hide Simpler
- Quit Simpler
- Simpler Help

Or is there an easier way to change it via the info.plist? - I tried changing bundle name, bundle display name and it didn't seem to work.

**Comment by mortenjust** [comment]
Fixed in 1.31 - thanks for reporting!
