### ISSUE TITLE
"Wrong" words do not make a sound and do not get immediately removed.

### ISSUE THREAD

**Issue by desertman** [mortenjust/cleartext-mac#6]
"Wrong" words do not make a sound and do not get immediately removed as shown in the demonstration. They just get highlighted. (1.0 and 1.2pre)

**Comment by artlung** [comment]
Same result - words get highlighted with yellow background color.

Version 1.1 MacOS 10.11.4.

**Comment by mortenjust** [comment]
Fixed in 1.3
