### ISSUE TITLE
Application broken in macOS Sierra

### ISSUE THREAD

**Issue by rogerolden** [mortenjust/cleartext-mac#72]
I cannot write with the app in macOS Sierra. There is no cursor and I cant type. Although I can still save the empty .txt document to my desktop.

**Comment by OKNoah** [comment]
Same problem. The app also crashed the first time I tried to open it.

**Comment by csanzol** [comment]
Does anyone solved this problem? :) Unfortunately I can not

**Comment by redasadki** [comment]
Same here.

**Comment by mortenjust** [comment]
Thanks for pointing this out. Check out the latest release, works on my Sierra
